wandb:
    entity: docvqa_nlp6
    project: layoutLM
    group: layoutLMv2
    experiment: test
    use_wandb: True # trainer에서 wandb를 사용할지 안할지
    online: True # 온라인으로 할지 오프라인으로 할지

save_dir : layoutLMv2
do_predict: True

data:
    train_load: Ssunbell/boostcamp-docvqa-v2
    val_load: Ssunbell/boostcamp-docvqa-v2
    test_load: Ssunbell/boostcamp-docvqa-v2-test
    preprocess: LayoutLMPreprocess
    
model:
    model_name : microsoft/layoutlmv2-large-uncased
    model_class : BaselineModel
    trainer_class: BaselineTrainer
    metric_class : Metrics_nbest
    optimizer : AdamW

train:
    batch_size: 8
    test_batch_size: 8
    max_epoch: 2
    dropout_rate : 0.1
    learning_rate: 5e-6
    num_workers: 4
    max_length : 512
    stride : 128
    n_best_size : 20
    max_answer_length: 20
    seed: 42
    gpus: 1